name: Coverity Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverity:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install dependencies
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            gcc \
            make \
            wget \
            curl \
            tar

      # Download Coverity Build Tool
      - name: Download Coverity Tool
        run: |
          wget https://scan.coverity.com/download/linux64 \
            --post-data "token=${{ secrets.COVERITY_SCAN_TOKEN }}&project=hugleemink%2Fcoverity-scan-demo" \
            -O coverity_tool.tgz

          mkdir coverity_tool

          tar -xzf coverity_tool.tgz \
            --strip-components=1 \
            -C coverity_tool

          echo "========== Coverity Files =========="
          ls -la coverity_tool/bin

      # Debug repository
      - name: Show Repository
        run: |
          echo "Current directory:"
          pwd
          echo ""
          ls -R

      # Test build
      - name: Test Build
        run: |
          make clean
          make all

      # Capture build
      - name: Capture Build
        run: |
          rm -rf cov-int

          coverity_tool/bin/cov-build \
            --dir cov-int \
            make all

      # Verify output
      - name: Verify Capture
        run: |
          echo "Capture completed"
          ls -R cov-int

      # Package result
      - name: Package Analysis
        run: |
          tar czf analysis.tgz cov-int

      # Upload to Coverity Scan
      - name: Upload Analysis
        run: |
          curl \
            --form token="${{ secrets.COVERITY_SCAN_TOKEN }}" \
            --form email="${{ secrets.COVERITY_EMAIL }}" \
            --form file=@analysis.tgz \
            --form version="${{ github.sha }}" \
            --form description="GitHub Actions Coverity Scan" \
            "https://scan.coverity.com/builds?project=hugleemink%2Fcoverity-scan-demo"

      - name: Done
        run: echo "Coverity Scan Finished Successfully!"
